config/routes.rb
  get 'find_variant_shipping_cost', to: 'sections#find_variant_shipping_cost', :as => "find_variant_shipping_cost"
  get 'find_cart_extra_cost', to: 'carts#find_cart_extra_cost', :as => "find_cart_extra_cost"
  get 'find_cart_availability', to: 'carts#find_cart_availability', :as => "find_cart_availability"
  resources :bank_accounts
  resources :cart_items
  resources :carts, :only =>[:show, :destroy, :edit, :update, :create, :index, :empty_cart] do 
    get 'pre_order', to: 'carts#pre_order', :as => "pre_order"
    get 'payment', to: 'carts#payment', :as => "payment"
    match 'payu_callback', to: 'carts#payu_return', via: :all
    get 'check_captcha', to: 'carts#check_captcha', :as => "check_captcha"
    get 'empty_cart', to: 'carts#empty_cart', :as => "empty_cart"
  end    

  resources :sections do 
    get 'sections/:id/:pid/add_to_cart', to: "sections#add_to_cart", :as => "add_to_cart"
    get 'searchs', to: 'sections#show'
    get ':productid', to: 'sections#showcase', as: :product_show
    get 'main_others', to: 'sections#main_others', :as => "main"
    get 'sub_others', to: 'sections#sub_others', :as => "sub" 
    collection { post :searchs, to: 'sections#show' }
    collection { get :searchs, to: 'sections#show' }
  end

  get 'check_user_login', to: 'sections#check_user_login', :as => "check_user_login"

  namespace :support do
    resources :ticket_tasks
    resources :ticket_replies
    resources :tickets
    get 'dashboard', to: 'supports#dashboard', :as => "dashboard"
    resources :orders do
      resources :order_revocation
      resources :shipments
    end
    resources :users do 
      resources :vouchers
    end
    resources :consignments
  end

  namespace :admin do
    resources :availability_plans do
      get 'find_country_pincode_with_id', to: 'availability_plans#find_country_pincode_with_id'
      resources :plan_countries do 
        resources :country_pincodes 
      end
    end
    resources :cod_policies do 
      get 'find_cod_country_pincode_with_id', to: 'cod_policies#find_cod_country_pincode_with_id'
      resources :cod_specific_countries do 
        resources :cod_specific_pincodes
      end
    end
    resources :price_ranges
    resources :weight_ranges
    resources :shipping_prices
    resources :shipping_weights
    resources :shipping_policies do
      get 'find_shipping_policy_shipping_weight', to: 'shipping_policies#find_shipping_policy_shipping_weight'
      resources :shipping_specific_countries do
        resources :shipping_specific_pincodes
      end
    end
    resources :failure_transactions
    resources :pages do
      post :delete_selected_page, :on => :collection
    end

    resources :sms_notifications
    resources :image_types do 
      resources :general_images do
        collection { post :sort }
      end
    end
    resources :wishlists
    resources :ticket_tasks
    resources :ticket_replies
    resources :refund_revocation_items
    resources :refund_revocations
    resources :replacement_revocations do 
      
    end
    resources :replacement_revocation_items
    resources :vouchers
    resources :pickup_tasks_pickup_consignments
    resources :pickup_consignments do
      
    end
    resources :pickup_consignment_items do 
      get 'pickup_consign_item_not_recevied', to: "pickup_consignment_items#pickup_consign_item_not_recevied"
      get 'pickup_consign_item_recevied', to: "pickup_consignment_items#pickup_consign_item_recevied"
    end
    resources :pickup_consignment_invoices
    resources :notification_customers
    resources :consignment_item_revocations
    resources :consignment_revocations
    resources :order_revocation_items
    resources :order_revocations
    resources :package_tasks_consignments, :only =>[:index, :destroy]
    resources :consignment_items
    resources :logistics
    get 'new_store', to: 'generals#new_store', :as => "new_store"    
    get 'check_image_type_exist' =>"image_types#check_image_type_exist"
    get 'check_image_name_exist' =>"image_types#check_image_name_exist"
    get 'check_plan_name_exist' =>"availability_plans#check_plan_name_exist"
    get 'check_brand_name_exist' =>"brands#check_brand_name_exist"
    get 'check_page_name_exist' =>"pages#check_page_name_exist"
    get 'check_weight_range_exist' =>"weight_ranges#check_weight_range_exist"    
    get 'check_price_range_exist' =>"price_ranges#check_price_range_exist"
    resources :generals do
      get 'edit_acc_spec', to: 'generals#edit_acc_spec', :as => "edit_acc_spec"
      get 'edit_seo_spec', to: 'generals#edit_seo_spec', :as => "edit_seo_spec"
      get 'edit_social_spec', to: 'generals#edit_social_spec', :as => "edit_social_spec"
    end
    resources :order_items do 
      get 'check_order_item_availability', to: 'order_items#check_order_item_availability'
    end 
    get 'dashboard',to: "admins#dashboard"
    resources :rejection_reasons
    resources :carts  
    resources :warehouse_dashboard do
      resources :warehouse_ticket_tasks
      resources :warehouse_ticket_replies
      resources :resend_tasks do
        get 'resend_consignments/:id', to: 'resend_consignments#show' ,:as => "consignment_show"
      end
      resources :resend_consignments 
      resources :resend_tasks_consignments
      resources :package_tasks do
        get 'consignments/', to: 'package_tasks#index' 
        get 'consignments/:id', to: 'consignments#show' ,:as => "task_consignment_show"
        get 'consignments/:id/consignment_logs', to: 'consignments#consignment_logs', :as => "consignment_logs"
      end
      resources :pickup_tasks do 
        get 'assigned_pickup_consignments/:id', to: 'assigned_pickup_consignments#show' ,:as => "pickup_consignment_show_path"
        resources :assigned_pickup_consignments do        
          
        end
      end
      resources :consignments, :except => [:show]
      resources :assigned_pickup_consignments
      get 'consignments/:id', to: 'consignments#index'
      resources :stocks
      get '/stocks', to: 'stocks#index'
      get '/stocks/:id', to: 'stocks#show'
      get 'orders/:id', to: 'warehouse_dashboard#orders', :as => "orders"
    end 
    resources :orders do 
      resources :shipments
      get 'shipments/:id', to: 'shipments#show', :as => "shipment_show"
      get 'order_logs', to: 'orders#order_logs', :as => "order_logs"
      get 'find_variant_with_sku', to: 'orders#find_variant_with_sku'
    end
    get 'brands/remove_product_from_brand', to: "brands#remove_product_from_brand"
    get 'categories/remove_product_from_category', to: "categories#remove_product_from_category"
    resources :generals 
    resources :warehouses_roles
    resources :product_properties
    resources :child_categories
    resources :categories do
      get ':product_id/to_display', to: "categories#to_display", :as => "to_display"
      get 'make_active', to: "categories#make_active"
      collection { post :sort }
      collection { post :promotion_sort }
      collection { post :remove_product_from_category }
    end
    resources :types
    resources :images do
      collection { post :sort }
      collection { post :banner_sort }
      collection { post :parent_image_sort }
      collection { post :child_image_sort }
    end
    resources :invoices
    resources :products_tax_plans
    resources :child_products
    resources :product_shipping_plans    
    resources :inventories
    resources :values
    resources :specifications    
    resources :brands do
      collection { post :remove_product_from_brand }
      post :delete_selected, :on => :collection
      post :delete_selected_brand, :on => :collection
    end
    resources :product_questions
    resources :permissions

    resources :shipping_plans do
      resources :shipping_countries do
        resources :shipping_states do
          resources :shipping_cities do
            resources :shipping_costs
          end
        end
      end
    end
    
    resources :warehouses do
      resources :addresses
    end

    resources :vendors do
      resources :addresses
    end

    resources :products do
      get 'cod_activate', to: "products#cod_activate", :as => "cod_activate" 
      resources :variants do 
        resources :inventories do 
          resources :regulations
        end
        collection { post :sort }
      end
      collection { post :sort }
      collection { post :promotion_sort }
      collection { post :promotion_update }
    end
   
    get 'find_state_city_pincode', to: "countries#find_state_city_pincode", :as => "find_state_city_pincode" 
    get 'countries/autocomplete/:search_param', to: "countries#autocomplete", :as => "countries_autocomplete" 
    resources :countries do 
      collection { post :import }
      resources :states do
        collection { post :import } 
        
      end
    end
    
    resources :district_cities do
      collection { post :import }
      resources :pincodes
    end
    
    resources :users do
      get 'orders', to: 'users#orders', :as => "orders"
      resources :addresses
      resources :profiles, :except => [:index, :destroy]
    end

    resources :roles do
      resources :block_lists
    end
    get 'for_blocklist', to: 'roles#for_blocklist', :as => "for_blocklist"

    resources :tax_plans do
      resources :tax_countries do
        resources :tax_states do
          resources :tax_cities
        end
      end
    end

  end

  root 'static_pages#index'
  get 'term-use', to: 'static_pages#term_use', as: :term_use
  get 'privacy', to: 'static_pages#privacy', as: :privacy
  get 'contact-us', to: 'static_pages#contact_us', as: :contact_us
  get 'help_desk', to: 'static_pages#help_desk', as: :help_desk

  get 'about-us', to: 'static_pages#about_us', as: :about_us
  get 'policy', to: 'static_pages#policy', as: :policy
  get '/:page_name', to: "static_pages#pageshow", :as => "pageshow"
  get "pages" => 'static_pages#pages', :as => 'pages'
  
 

app/models/admin/block_list.rb
# == Schema Information
#
# Table name: block_lists
#
#  id         :integer          not null, primary key
#  con_name   :string(255)
#  met_name   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  role_id    :integer
#

class Admin::BlockList < ActiveRecord::Base
  #GEMS USED
  #ACCESSORS
  #ASSOCIATIONS
  belongs_to :role
  #VALIDATIONS
  validates :con_name, :presence => true
  validates :met_name, :presence => true
  #CALLBACKS
  #SCOPES
  #CUSTOM SCOPES
  #OTHER METHODS
  #JOBS
  #PRIVATE 
end

app/controllers/admin/block_lists_controller.rb
class Admin::BlockListsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_block_list, only: [:show, :edit, :update, :destroy]
  before_action :find_role
  before_action :authorize

  def index 
    @block_lists = @role.block_lists.page(params[:page]).per(9)
  end
  
  def show     
  end

  def new    
    @block_list = Admin::BlockList.new
    @check1 = params[:check] unless params[:check].nil?
    @met = params[:act].constantize unless params[:act].nil? 
    if @met != ''
      @metod = @met.action_methods.each {|m| puts m } unless params[:act].nil?
    end 
    @role.block_lists.each do |x| 
      if x.con_name == params[:act]
        @block_listing = @block_listing.to_a.push x.met_name 
      end
    end
    @block_listing ||= ''
    @methods = @metod.reject{|y| @block_listing.include? y}  unless @metod.nil?
    @methods ||= @metod
    respond_to do |format|
      format.json { 
        render :json => @methods.to_json
      }
      format.html {}
    end
  end

  def edit
    @met = params[:act].constantize unless params[:act].nil?
    if @met != ''
      @met1 = @met.action_methods.each {|m| puts m } unless params[:act].nil?
    end
    if @met1.present?
      render :json => @met1.to_json
    else
      if request.xhr?
        @render_path = edit_admin_role_block_list_path
        @render_file = 'admin/block_lists/edit'
        render "remote_content/common_render.js.erb"          
      else
        render :template => "admin/block_lists/edit"
      end
    end
  end

  def create
    @block_list = @role.block_lists.build(block_list_params)
    if @block_list.save
      @block_list = Admin::BlockList.new
      @block_lists = @role.block_lists
      if request.xhr?
        flash[:alert] = 'Block list was successfully created.'
        @render_path = admin_role_path(@role)
        @render_file = 'admin/roles/show'
        render "remote_content/common_render.js.erb"          
      else
        render :template => "admin/roles/show"
      end
    else 
      render :template => "admin/roles/show"
    end
  end

  def update
    if @block_list.update(block_list_params)
      redirect_to admin_role_path(@role), notice: 'Block list was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @block_list.destroy
    if request.xhr?
      flash[:alert] = 'Block list was successfully destroyed.'
      @render_path = admin_role_path(@role)
      @block_lists = @role.block_lists
      @block_list = Admin::BlockList.new
      @render_file = 'admin/roles/show'
      render "remote_content/common_render.js.erb"          
    else
      render :template => "admin/roles/show"
    end
  end

  private
    def set_block_list
      @block_list = Admin::BlockList.find(params[:id])
    end

    def block_list_params
      params.require(:admin_block_list).permit(:con_name, :met_name)
    end

    def find_role
      @role = Admin::Role.find(params[:role_id])
    end
end

app/views/admin/block_lists/_form.html.erb
<%= form_for @block_list, :url => admin_role_block_lists_path(@role),:html => {:id => 'blocks_form' } do |f| %>
  <span id="urlsd" style="display:none;">new</span>
  <% if @block_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block_list.errors.count, "error") %> prohibited this block_list from being saved:</h2>
      <ul>
      <% @block_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br/><br/>
  <div class="field">
    <%= f.label :con_name,"Controller Name" %><br>
    <%= f.select :con_name, options_for_select(Array[*ApplicationController.descendants.collect {|v,i| [v,v] }]),{ :prompt => 'Select' }, :class => "form-control width controller_name" %>
    <span id="controller_name_error1" class="error_list" style="display:none;"></span>
  </div><br />
  <div class="field met_field">
    <%= f.label :met_name,"Method Name" %><br>
    <%= f.select :met_name, options_for_select(""),{}, :class => "form-control width action_name" %>
    <span id="action_name_error1" class="error_list" style="display:none;"></span>
  </div><br/>
  <div class="actions">
    <%= f.submit "Block", :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/block_lists/edit.html.erb
<div class="breadcrumbs" id="breadcrumbs">

  <!-- breadcrumb start -->
  <ul class="breadcrumb"> 
    <li><i class="ace-icon fa fa-binoculars home-icon"></i>&nbsp;&nbsp;<%= link_to "Roles", admin_roles_path,:remote => true %></li>
    <li class="markthis"><%= link_to @role.name.capitalize , admin_role_path(@role),:remote => true %></li>
    <li class="active">Edit Block List</li>
  </ul><!-- breadcrumb end -->

  <!-- button panel start -->
  <div class="pull-right">
  </div>
  <!-- button panel end --> 
 
</div>

  <div class="page-content">
    <!-- flash start --> 
    <div class="flash_message_panel" >
      <%= render partial: "layouts/shared/flash_msg" %> 
    </div>
    <!-- flash end -->
    <div class ="row">
      <div class="col-xs-12 col-sm-8">
               <div class="widget-container-col ui-sortable">
          <div class="widget-box widget-color-blue ui-sortable-handle">
            <div class="widget-header">
              <h5 class="widget-title lighter bigger  cursive-font">Edit Block List</h5>
              <div class="widget-toolbar">
              </div>
            </div>
            <div class="widget-body">
              <div class="widget-main">
                 <%= form_for @block_list, :url => admin_role_block_list_path(@role, @block_list),:html => {:id => 'blocks_form'},:remote => true do |f| %>
                  <span id="urlsd" style="display:none;">edit</span>
                  <br/><br/> 
                  <div class="row">
                    <div class="col-sm-2 col-xs-12">
                      <%= f.label :con_name, "Controller",:class => "label-color" %><br>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                      <%= f.select :con_name, options_for_select(Array[*ApplicationController.descendants.collect {|v,i| [v,v] }], {:selected =>  @block_list.con_name}),{ :prompt => 'Select' }, :class => "form-control blue_textbox  controller_name" %>
                    </div>
                    <div class="col-sm-3 col-xs-12">
                       <span id="controller_name_error1" class="error_list" style="display:none;"></span>
                    </div>
                </div><br />
                  <div class="row">
                    <div class="col-sm-2 col-xs-12">
                      <%= f.label :met_name, "Method",:class => "label-color" %><br>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                      <%= f.select :met_name, options_for_select(Array[*@block_list.con_name.constantize.action_methods.collect { |w,j| w }], {:selected =>  @block_list.met_name}),{ :prompt => 'Select' }, :class => "form-control blue_textbox  action_name" %>
                    </div>
                    <div class="col-sm-3 col-xs-12">
                         <span id="action_name_error1" class="error_list" style="display:none;"></span>
                    </div>
                </div><br />
                  <br/>
                  <div class="actions">
                    <%= f.submit "Update Blocklist", :class => "btn btn-primary btn-sm" %>    
                  </div>
                <% end %><br/>
              </div>
            </div>
          </div>
        </div>

        
      </div>
    </div>
  </div>

app/views/admin/block_lists/index.html.erb
<%= render partial: "layouts/shared/flash_msg" %>    
<div class="border">
  <div class="pull-right">
  <% if check_link(new_admin_role_block_list_path(@role)) %>
  <%= link_to 'New Block List', new_admin_role_block_list_path(@role) , :class => "btn btn-success"%>
  <% end %></div>
  <h3>Listing Block Lists</h3>
</div><br/>
<div class="panel panel-default">
  <div class=" panel-heading">
    <div class="row">
      <div class="col-sm-5 text-primary">Controller Name</div>
      <div class="col-sm-3 text-primary">Method name</div>
      <div class="col-sm-2 text-primary">Edit</div>
      <div class="col-sm-2 text-primary">Delete</div>
    </div>
  </div>
  <div class="panel-body">
    <% @block_lists.each do |block_list| %>
      <div class="row hoverd">
        <div class="col-sm-5 col-xs-8"><%= block_list.con_name %></div>
        <div class="col-sm-3 col-xs-2"><%= block_list.met_name %></div>
        <div class="col-sm-2 col-xs-1">
        <% if check_link(edit_admin_role_block_list_path(@role, block_list)) %>
          <a class="glyphicon glyphicon-pencil text-success" href="<%= edit_admin_role_block_list_path(@role, block_list) %>"></a>
        <% end %>
        </div>
        <div class="col-sm-2 col-xs-1">
        <% if check_link(admin_role_block_list_path(@role, block_list)) %>
          <%= link_to '', admin_role_block_list_path(@role, block_list), method: :delete, data: { confirm: 'Are you sure?' },:class => "glyphicon glyphicon-trash text-danger" %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/block_lists/new.html.erb
<%= render partial: "layouts/shared/flash_msg" %>    
<div class="border">
	<% if check_link(admin_role_block_lists_path(@role)) %>
	  <%= link_to 'List Block List', admin_role_block_lists_path(@role), :class => "btn btn-primary btn-sm pull-right" %>
	<% end %>
	<h3>New block_list</h3>
</div>	
<ol class="breadcrumb">
	<% if check_link(admin_roles_path) %>
	  <li><%= link_to "Roles", admin_roles_path %></li>
	<% end %>
	<% if check_link(admin_role_path(@role)) %>
	  <li><%= link_to 'Show Roles', admin_role_path(@role) %></li>
	<% end %>
	<li class="active">New Block List</li>
</ol>
<%= render 'form' %><br />		