config/routes.rb
  get 'find_variant_shipping_cost', to: 'sections#find_variant_shipping_cost', :as => "find_variant_shipping_cost"
  get 'find_cart_extra_cost', to: 'carts#find_cart_extra_cost', :as => "find_cart_extra_cost"
  get 'find_cart_availability', to: 'carts#find_cart_availability', :as => "find_cart_availability"
  resources :bank_accounts
  resources :cart_items
  resources :carts, :only =>[:show, :destroy, :edit, :update, :create, :index, :empty_cart] do 
    get 'pre_order', to: 'carts#pre_order', :as => "pre_order"
    get 'payment', to: 'carts#payment', :as => "payment"
    match 'payu_callback', to: 'carts#payu_return', via: :all
    get 'check_captcha', to: 'carts#check_captcha', :as => "check_captcha"
    get 'empty_cart', to: 'carts#empty_cart', :as => "empty_cart"
  end    

  resources :sections do 
    get 'sections/:id/:pid/add_to_cart', to: "sections#add_to_cart", :as => "add_to_cart"
    get 'searchs', to: 'sections#show'
    get ':productid', to: 'sections#showcase', as: :product_show
    get 'main_others', to: 'sections#main_others', :as => "main"
    get 'sub_others', to: 'sections#sub_others', :as => "sub" 
    collection { post :searchs, to: 'sections#show' }
    collection { get :searchs, to: 'sections#show' }
  end

  get 'check_user_login', to: 'sections#check_user_login', :as => "check_user_login"

  namespace :support do
    resources :ticket_tasks
    resources :ticket_replies
    resources :tickets
    get 'dashboard', to: 'supports#dashboard', :as => "dashboard"
    resources :orders do
      resources :order_revocation
      resources :shipments
    end
    resources :users do 
      resources :vouchers
    end
    resources :consignments
  end

  namespace :admin do
    resources :availability_plans do
      get 'find_country_pincode_with_id', to: 'availability_plans#find_country_pincode_with_id'
      resources :plan_countries do 
        resources :country_pincodes 
      end
    end
    resources :cod_policies do 
      get 'find_cod_country_pincode_with_id', to: 'cod_policies#find_cod_country_pincode_with_id'
      resources :cod_specific_countries do 
        resources :cod_specific_pincodes
      end
    end
    resources :price_ranges
    resources :weight_ranges
    resources :shipping_prices
    resources :shipping_weights
    resources :shipping_policies do
      get 'find_shipping_policy_shipping_weight', to: 'shipping_policies#find_shipping_policy_shipping_weight'
      resources :shipping_specific_countries do
        resources :shipping_specific_pincodes
      end
    end
    resources :failure_transactions
    resources :pages do
      post :delete_selected_page, :on => :collection
    end

    resources :sms_notifications
    resources :image_types do 
      resources :general_images do
        collection { post :sort }
      end
    end
    resources :wishlists
    resources :ticket_tasks
    resources :ticket_replies
    resources :refund_revocation_items
    resources :refund_revocations
    resources :replacement_revocations do 
      
    end
    resources :replacement_revocation_items
    resources :vouchers
    resources :pickup_tasks_pickup_consignments
    resources :pickup_consignments do
      
    end
    resources :pickup_consignment_items do 
      get 'pickup_consign_item_not_recevied', to: "pickup_consignment_items#pickup_consign_item_not_recevied"
      get 'pickup_consign_item_recevied', to: "pickup_consignment_items#pickup_consign_item_recevied"
    end
    resources :pickup_consignment_invoices
    resources :notification_customers
    resources :consignment_item_revocations
    resources :consignment_revocations
    resources :order_revocation_items
    resources :order_revocations
    resources :package_tasks_consignments, :only =>[:index, :destroy]
    resources :consignment_items
    resources :logistics
    get 'new_store', to: 'generals#new_store', :as => "new_store"    
    get 'check_image_type_exist' =>"image_types#check_image_type_exist"
    get 'check_image_name_exist' =>"image_types#check_image_name_exist"
    get 'check_plan_name_exist' =>"availability_plans#check_plan_name_exist"
    get 'check_brand_name_exist' =>"brands#check_brand_name_exist"
    get 'check_page_name_exist' =>"pages#check_page_name_exist"
    get 'check_weight_range_exist' =>"weight_ranges#check_weight_range_exist"    
    get 'check_price_range_exist' =>"price_ranges#check_price_range_exist"
    resources :generals do
      get 'edit_acc_spec', to: 'generals#edit_acc_spec', :as => "edit_acc_spec"
      get 'edit_seo_spec', to: 'generals#edit_seo_spec', :as => "edit_seo_spec"
      get 'edit_social_spec', to: 'generals#edit_social_spec', :as => "edit_social_spec"
    end
    resources :order_items do 
      get 'check_order_item_availability', to: 'order_items#check_order_item_availability'
    end 
    get 'dashboard',to: "admins#dashboard"
    resources :rejection_reasons
    resources :carts  
    resources :warehouse_dashboard do
      resources :warehouse_ticket_tasks
      resources :warehouse_ticket_replies
      resources :resend_tasks do
        get 'resend_consignments/:id', to: 'resend_consignments#show' ,:as => "consignment_show"
      end
      resources :resend_consignments 
      resources :resend_tasks_consignments
      resources :package_tasks do
        get 'consignments/', to: 'package_tasks#index' 
        get 'consignments/:id', to: 'consignments#show' ,:as => "task_consignment_show"
        get 'consignments/:id/consignment_logs', to: 'consignments#consignment_logs', :as => "consignment_logs"
      end
      resources :pickup_tasks do 
        get 'assigned_pickup_consignments/:id', to: 'assigned_pickup_consignments#show' ,:as => "pickup_consignment_show_path"
        resources :assigned_pickup_consignments do        
          
        end
      end
      resources :consignments, :except => [:show]
      resources :assigned_pickup_consignments
      get 'consignments/:id', to: 'consignments#index'
      resources :stocks
      get '/stocks', to: 'stocks#index'
      get '/stocks/:id', to: 'stocks#show'
      get 'orders/:id', to: 'warehouse_dashboard#orders', :as => "orders"
    end 
    resources :orders do 
      resources :shipments
      get 'shipments/:id', to: 'shipments#show', :as => "shipment_show"
      get 'order_logs', to: 'orders#order_logs', :as => "order_logs"
      get 'find_variant_with_sku', to: 'orders#find_variant_with_sku'
    end
    get 'brands/remove_product_from_brand', to: "brands#remove_product_from_brand"
    get 'categories/remove_product_from_category', to: "categories#remove_product_from_category"
    resources :generals 
    resources :warehouses_roles
    resources :product_properties
    resources :child_categories
    resources :categories do
      get ':product_id/to_display', to: "categories#to_display", :as => "to_display"
      get 'make_active', to: "categories#make_active"
      collection { post :sort }
      collection { post :promotion_sort }
      collection { post :remove_product_from_category }
    end
    resources :types
    resources :images do
      collection { post :sort }
      collection { post :banner_sort }
      collection { post :parent_image_sort }
      collection { post :child_image_sort }
    end
    resources :invoices
    resources :products_tax_plans
    resources :child_products
    resources :product_shipping_plans    
    resources :inventories
    resources :values
    resources :specifications    
    resources :brands do
      collection { post :remove_product_from_brand }
      post :delete_selected, :on => :collection
      post :delete_selected_brand, :on => :collection
    end
    resources :product_questions
    resources :permissions

    resources :shipping_plans do
      resources :shipping_countries do
        resources :shipping_states do
          resources :shipping_cities do
            resources :shipping_costs
          end
        end
      end
    end
    
    resources :warehouses do
      resources :addresses
    end

    resources :vendors do
      resources :addresses
    end

    resources :products do
      get 'cod_activate', to: "products#cod_activate", :as => "cod_activate" 
      resources :variants do 
        resources :inventories do 
          resources :regulations
        end
        collection { post :sort }
      end
      collection { post :sort }
      collection { post :promotion_sort }
      collection { post :promotion_update }
    end
   
    get 'find_state_city_pincode', to: "countries#find_state_city_pincode", :as => "find_state_city_pincode" 
    get 'countries/autocomplete/:search_param', to: "countries#autocomplete", :as => "countries_autocomplete" 
    resources :countries do 
      collection { post :import }
      resources :states do
        collection { post :import } 
        
      end
    end
    
    resources :district_cities do
      collection { post :import }
      resources :pincodes
    end
    
    resources :users do
      get 'orders', to: 'users#orders', :as => "orders"
      resources :addresses
      resources :profiles, :except => [:index, :destroy]
    end

    resources :roles do
      resources :block_lists
    end
    get 'for_blocklist', to: 'roles#for_blocklist', :as => "for_blocklist"

    resources :tax_plans do
      resources :tax_countries do
        resources :tax_states do
          resources :tax_cities
        end
      end
    end

  end

  root 'static_pages#index'
  get 'term-use', to: 'static_pages#term_use', as: :term_use
  get 'privacy', to: 'static_pages#privacy', as: :privacy
  get 'contact-us', to: 'static_pages#contact_us', as: :contact_us
  get 'help_desk', to: 'static_pages#help_desk', as: :help_desk

  get 'about-us', to: 'static_pages#about_us', as: :about_us
  get 'policy', to: 'static_pages#policy', as: :policy
  get '/:page_name', to: "static_pages#pageshow", :as => "pageshow"
  get "pages" => 'static_pages#pages', :as => 'pages'
  
 

app/models/admin/state.rb
# == Schema Information
#
# Table name: states
#
#  id         :integer          not null, primary key
#  country_id :string(255)
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  state_code :string(255)
#

class Admin::State < ActiveRecord::Base
  #GEMS USED
  #ASSOCIATIONS
  belongs_to :country
  has_many :district_cities, class_name: "Admin::DistrictCity", dependent: :destroy
  has_many :pincodes, through: :district_cities, class_name: "Admin::Pincode"
  #VALIDATIONS
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 30 }
  #validates :state_code, :presence => true, :uniqueness => true, :length => { :maximum => 10 }
  #CALLBACKS
  #SCOPES
  #CUSTOM SCOPES
  #OTHER METHODS
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Admin::State.create! row.to_hash
    end
  end 
  #JOBS
  #PRIVATE
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_country
  before_action :set_state, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  def index
    @search =  @country.states.search(params[:q])
    @states = @search.result
    if request.xhr?
      @render_path = admin_country_states_path(@country)
      @render_file = 'admin/states/index'
      render "remote_content/common_render.js.erb"          
    else
      render :template => "admin/states/index"
    end
  end

  def import
    Admin::State.import(params[:file])
    redirect_to admin_country_path(@country), notice: "States imported."
  end

  def show
    @district_cities = @state.district_cities
    if request.xhr?
      @render_path = admin_country_state_path(@country,@state)
      @render_file = 'admin/states/show'
      render "remote_content/common_render.js.erb"          
    else
      render :template => "admin/states/show"
    end
  end

  def new
    @state = Admin::State.new
    if request.xhr?
      @render_path = new_admin_country_state_path(@country)
      @render_file = 'admin/states/new'
      render "remote_content/common_render.js.erb"          
    else
      render :template => "admin/states/new"
    end
  end

  def edit
    if request.xhr?
      @render_path = edit_admin_country_state_path(@country,@state)
      @render_file = 'admin/states/edit'
      render "remote_content/common_render.js.erb"          
    else
      render :template => "admin/states/edit"
    end
  end 

  def create
    @state = @country.states.build(state_params)
    if @state.save
      flash[:alert] = 'State was successfully created.'
      @render_path = admin_country_state_path(@country,@state)
      @render_file = 'admin/states/show'
      render "remote_content/common_render.js.erb"
    else
      @state = Admin::State.new
      render :template => "admin/states/new"
    end
  end

  def update
    if @state.update(state_params)
      flash[:alert] = 'State was successfully updated.'
      @render_path = admin_country_states_path(@country)
      @render_file = 'admin/states/index'
      render "remote_content/common_render.js.erb"
    else
      render :template => "admin/states/edit"
    end
  end

  def destroy
    @state.destroy
    flash[:alert] = 'State was successfully destroyed.'
    @render_path = admin_country_states_path(@country)
    @render_file = 'admin/states/index'
    render "remote_content/common_render.js.erb"
  end

  private
    def set_state
      @state = Admin::State.find(params[:id])
    end

    def set_country
      @country = Admin::Country.find(params[:country_id])
    end

    def state_params
      params.require(:admin_state).permit(:country_id, :name , :state_code)
    end
end

app/views/admin/states/_form.html.erb
<%= form_for @state, :url => admin_country_states_path(@country), :html => {:id => 'new_state'},:remote => true do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>
      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,:class => "form-control width1",:id => "statename" %>
    <span id="state_name_error" class="error_list" style="display:none;"></span>
  </div><br/>
  <div class="field">
    <%= f.label :state_code %><br>
    <%= f.text_field :state_code, :class => "form-control width1",:id => "statecode" %>
    <span id="state_code_error" class="error_list" style="display:none;"></span>
  </div><br/>
  <div class="actions">
    <%= f.submit "Create State" , :class => "btn btn-success"%>
  </div>
<% end %>

app/views/admin/states/edit.html.erb
<%= render partial: "layouts/shared/flash_msg" %>  
<div class="border"><br/>
	<div class="pull-right markthis">					
		<%= link_to 'Show State', admin_country_state_path(@country, @state), :class => "btn btn-primary ",:remote => true %>
  </div>
	<div class="row">
    <div class="col-sm-6 col-xs-12">
      <ol class="breadcrumb">
        <li class="markthis"><%= link_to @country.name, admin_country_path(@country),:remote => true %></li>
        <li class="markthis"><%= link_to 'states', admin_country_states_path(@country),:remote => true %></li>     
        <li class="active">Edit State</li>
      </ol>
    </div>
  </div> 
</div><br />
<div class="row">
  <div class="col-xs-12 col-sm-6">
		<%= form_for @state, :url => admin_country_states_path(@country),:remote => true do |f| %>
		  <% if @state.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>
		      <ul>
		      <% @state.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <div class="field">
		    <%= f.label :name %><br>
		    <%= f.text_field :name,:class => "form-control width1",:id => "statename" %>
		  </div><br/>
		  <div class="field">
		    <%= f.label :state_code %><br>
		    <%= f.text_field :state_code,:class => "form-control width1",:id => "statecode" %>
		  </div><br/>
		  <div class="actions">
		    <%= f.submit "Create State" , :class => "btn btn-success"%>
		  </div>
		<% end %><br/><br/>	
  </div>	
</div>
	

app/views/admin/states/index.html.erb
<%= render partial: "layouts/shared/flash_msg" %>  
<div class="border"><br/>
  <div class="row">
    <div class="col-sm-3 col-xs-12">
      <ol class="breadcrumb">
        <li class="markthis"><%= link_to @country.name, admin_country_path(@country),:remote => true %></li>
        <li class="active">State</li>
      </ol>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= search_form_for(@search,:url => admin_country_states_path(@country),:html => {:id => 'search_form_for',:class => 'search_form_for'},:remote => true)  do |f| %><br/>
        <div class="row">
          <div class="col-sm-8 col-xs-12">
            <div class="col-sm-10 col-xs-12">               
              <%= f.text_field :name_eq_any,:class => "form-control", :placeholder => "State Name" %>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">              
            <%= f.submit "Search" , :id => "search1_form",:class => "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-3 col-xs-12"><br/>
      <div class="pull-right">
        <%= link_to 'Add New State', new_admin_country_state_path(@country) , :class => "btn btn-success",:remote => true %>
      </div>
    </div>
  </div>
</div><br/>
<div class ="row">
  <div class="col-xs-12 col-sm-8">    
    <div class="panel panel-default">
      <div class=" panel-heading">
        <div class="row">
          <div class="col-sm-5 col-xs-5 text-primary">State Name</div>
          <div class="col-sm-6 col-xs-6 text-primary">ISO</div>
          <div class="col-sm-1 col-xs-1 text-primary">Edit</div>
        </div>
      </div>
      <div class="panel-body top_space">
        <% @states.each do |state| %>
          <div class="row hoverd">
            <div class="col-sm-5 col-xs-5"><%= link_to_if(check_link(admin_country_state_path(@country, state)),state.name, admin_country_state_path(@country, state),:remote => true) %></div>
            <div class="col-sm-6 col-xs-6"><%= state.state_code %></div>
            <div class="col-sm-1 col-xs-1">
              <%= link_to '', edit_admin_country_state_path(@country, state) , :class => "glyphicon glyphicon-pencil text-success",:remote => true %>
            </div>       
          </div>          
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
  </div>
</div>
  

app/views/admin/states/new.html.erb
<%= render partial: "layouts/shared/flash_msg" %>  
<div class="border"><br/>
	<div class="pull-right">				
  </div>
	<div class="row">
    <div class="col-sm-6 col-xs-12">
      <ol class="breadcrumb">
	  		<li class="markthis"><%= link_to @country.name, admin_country_path(@country),:remote => true %></li>
	  		<li class="markthis"><%= link_to 'List States', admin_country_states_path(@country),:remote => true %></li>
  			<li class="active">New State</li>
      </ol>
    </div>
  </div> 
</div><br />
<div class ="row">
  <div class="col-xs-12 col-sm-6">
    <%= render 'form' %><br/><br/>	
  </div>	
</div>
	

app/views/admin/states/show.html.erb
  <%= render partial: "layouts/shared/flash_msg" %>  
  <div class="border"><br/>
    <div class="pull-right">
      <%= link_to "Add New District", new_admin_country_state_district_city_path(@country,@state) , :class => "btn btn-success",:remote => true %>
      <%= link_to 'Edit State', edit_admin_country_state_path(@country, @state), :class => "btn btn-primary ",:remote => true %>
      <%= link_to ' Delete', admin_country_state_path(@country, @state), method: :delete, data: { confirm: 'Are you sure?' },:class => " btn btn-danger gly",:remote => true %>
    </div>
    <div class="row">
      <div class="col-sm-6 col-xs-12">
        <ol class="breadcrumb">
          <li class="markthis"><%= link_to @country.name, admin_country_states_path(@country),:remote => true %></li> 
          <li class="markthis"><%= link_to 'states', admin_country_states_path(@country),:remote => true %></li>
          <li class="active"><%= @state.name.capitalize %>(<%= @state.state_code %>)</li>
        </ol>
      </div>
    </div>
  </div><br/>
  <div class="">
    <div class="row">
      <div class="col-sm-4 col-xs-4">
        <strong>Country</strong>
      </div>
      <div class="col-sm-6 col-xs-6">
        <%= @country.name %>
      </div>
    </div><br/>
  </div>
  <% if @district_cities.present? %>
    <div class ="row">
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class=" panel-heading">
          <div class="row">
            <div class="col-sm-5 col-xs-5 text-info bold">District Name</div>
            <div class="col-sm-5 col-xs-5 text-info bold">District Code</div>
            <div class="col-sm-1 col-xs-1 text-info bold">Delete</div>
            <div class="col-sm-1 col-xs-1 text-info bold">Edit</div>
          </div>
        </div>
        <div class="panel-body top_space">
          <% @district_cities.each do |district_city| %>
            <div class="row hoverd">
              <div class="col-sm-5 col-xs-5"><%= link_to district_city.name, admin_country_state_district_city_path(@country, @state, district_city),:remote => true %></div>
              <div class="col-sm-5 col-xs-5"><%= district_city.district_code %></div>
              <div class="col-sm-1 col-xs-1 markthis">
                <%= link_to '', admin_country_state_district_city_path(@country, @state, district_city), method: :delete, data: { confirm: 'Are you sure?' },:class => "glyphicon glyphicon-trash text-danger",:remote => true %>
              </div>
              <div class="col-sm-1 col-xs-1 markthis">
                <%= link_to '', edit_admin_country_state_district_city_path(@country, @state, district_city),:class => "glyphicon glyphicon-pencil text-success",:remote => true %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %><br/><br/>
        <span class="text-muted">no district is there to display.
         click this link to add district <%= link_to "Add New Disrtict", new_admin_country_state_district_city_path(@country,@state),:remote => true %>
        </span>
      <% end %>
    </div> 
  </div>`
</div>
	