config/routes.rb
Rails.application.routes.draw do    

  resources :wishlists, :only =>[:create]
  resources :subscribers
  devise_for :users, :controllers=> { :passwords => "passwords", :sessions => "sessions", :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, except:[:index] do
    resources :wishlists , :except => [:create]
    resources :wishlist_items
    resources :vouchers
    resources :orders do
      get 'consignment/:id',to: "orders#consignment", :as => "consignment_pdf"
      resources :shipping_address
    end
    resources :shipping_addresses
    resources :profiles, :except => [:index, :destroy]
    get 'account',to: "users#account"
    get 'address',to: "users#address"
    get 'address_create',to: "users#address_create", :as => "address_create"
  end 
  get '/carts', to: redirect('/') 
  get 'find_variant_shipping_cost', to: 'sections#find_variant_shipping_cost', :as => "find_variant_shipping_cost"
  get 'find_cart_extra_cost', to: 'carts#find_cart_extra_cost', :as => "find_cart_extra_cost"
  get 'find_cart_availability', to: 'carts#find_cart_availability', :as => "find_cart_availability"
  resources :bank_accounts
  resources :cart_items
  resources :carts, :only =>[:show, :destroy, :edit, :update, :create, :index, :empty_cart] do 
    get 'pre_order', to: 'carts#pre_order', :as => "pre_order"
    get 'payment', to: 'carts#payment', :as => "payment"
    match 'payu_callback', to: 'carts#payu_return', via: :all
    get 'check_captcha', to: 'carts#check_captcha', :as => "check_captcha"
    get 'empty_cart', to: 'carts#empty_cart', :as => "empty_cart"
  end    

  resources :sections do 
    get 'sections/:id/:pid/add_to_cart', to: "sections#add_to_cart", :as => "add_to_cart"
    get 'searchs', to: 'sections#show'
    get ':productid', to: 'sections#showcase', as: :product_show
    get 'main_others', to: 'sections#main_others', :as => "main"
    get 'sub_others', to: 'sections#sub_others', :as => "sub" 
    collection { post :searchs, to: 'sections#show' }
    collection { get :searchs, to: 'sections#show' }
  end

  get 'check_user_login', to: 'sections#check_user_login', :as => "check_user_login"

  namespace :support do
    resources :ticket_tasks
    resources :ticket_replies
    resources :tickets
    get 'dashboard', to: 'supports#dashboard', :as => "dashboard"
    resources :orders do
      resources :order_revocation
      resources :shipments
    end
    resources :users do 
      resources :vouchers
    end
    resources :consignments
  end

  namespace :admin do
    resources :availability_plans do
      get 'find_country_pincode_with_id', to: 'availability_plans#find_country_pincode_with_id'
      resources :plan_countries do 
        resources :country_pincodes 
      end
    end
    resources :cod_policies do 
      get 'find_cod_country_pincode_with_id', to: 'cod_policies#find_cod_country_pincode_with_id'
      resources :cod_specific_countries do 
        resources :cod_specific_pincodes
      end
    end
    resources :price_ranges
    resources :weight_ranges
    resources :shipping_prices
    resources :shipping_weights
    resources :shipping_policies do
      get 'find_shipping_policy_shipping_weight', to: 'shipping_policies#find_shipping_policy_shipping_weight'
      resources :shipping_specific_countries do
        resources :shipping_specific_pincodes
      end
    end
    resources :failure_transactions
    resources :pages do
      post :delete_selected_page, :on => :collection
    end

    resources :sms_notifications
    resources :image_types do 
      resources :general_images do
        collection { post :sort }
      end
    end
    resources :wishlists
    resources :ticket_tasks
    resources :ticket_replies
    resources :refund_revocation_items
    resources :refund_revocations
    resources :replacement_revocations do 
      
    end
    resources :replacement_revocation_items
    resources :vouchers
    resources :pickup_tasks_pickup_consignments
    resources :pickup_consignments do
      
    end
    resources :pickup_consignment_items do 
      get 'pickup_consign_item_not_recevied', to: "pickup_consignment_items#pickup_consign_item_not_recevied"
      get 'pickup_consign_item_recevied', to: "pickup_consignment_items#pickup_consign_item_recevied"
    end
    resources :pickup_consignment_invoices
    resources :notification_customers
    resources :consignment_item_revocations
    resources :consignment_revocations
    resources :order_revocation_items
    resources :order_revocations
    resources :package_tasks_consignments, :only =>[:index, :destroy]
    resources :consignment_items
    resources :logistics
    get 'new_store', to: 'generals#new_store', :as => "new_store"    
    get 'check_image_type_exist' =>"image_types#check_image_type_exist"
    get 'check_image_name_exist' =>"image_types#check_image_name_exist"
    get 'check_plan_name_exist' =>"availability_plans#check_plan_name_exist"
    get 'check_brand_name_exist' =>"brands#check_brand_name_exist"
    get 'check_page_name_exist' =>"pages#check_page_name_exist"
    get 'check_weight_range_exist' =>"weight_ranges#check_weight_range_exist"    
    get 'check_price_range_exist' =>"price_ranges#check_price_range_exist"
    resources :generals do
      get 'edit_acc_spec', to: 'generals#edit_acc_spec', :as => "edit_acc_spec"
      get 'edit_seo_spec', to: 'generals#edit_seo_spec', :as => "edit_seo_spec"
      get 'edit_social_spec', to: 'generals#edit_social_spec', :as => "edit_social_spec"
    end
    resources :order_items do 
      get 'check_order_item_availability', to: 'order_items#check_order_item_availability'
    end 
    get 'dashboard',to: "admins#dashboard"
    resources :rejection_reasons
    resources :carts  
    resources :warehouse_dashboard do
      resources :warehouse_ticket_tasks
      resources :warehouse_ticket_replies
      resources :resend_tasks do
        get 'resend_consignments/:id', to: 'resend_consignments#show' ,:as => "consignment_show"
      end
      resources :resend_consignments 
      resources :resend_tasks_consignments
      resources :package_tasks do
        get 'consignments/', to: 'package_tasks#index' 
        get 'consignments/:id', to: 'consignments#show' ,:as => "task_consignment_show"
        get 'consignments/:id/consignment_logs', to: 'consignments#consignment_logs', :as => "consignment_logs"
      end
      resources :pickup_tasks do 
        get 'assigned_pickup_consignments/:id', to: 'assigned_pickup_consignments#show' ,:as => "pickup_consignment_show_path"
        resources :assigned_pickup_consignments do        
          
        end
      end
      resources :consignments, :except => [:show]
      resources :assigned_pickup_consignments
      get 'consignments/:id', to: 'consignments#index'
      resources :stocks
      get '/stocks', to: 'stocks#index'
      get '/stocks/:id', to: 'stocks#show'
      get 'orders/:id', to: 'warehouse_dashboard#orders', :as => "orders"
    end 
    resources :orders do 
      resources :shipments
      get 'shipments/:id', to: 'shipments#show', :as => "shipment_show"
      get 'order_logs', to: 'orders#order_logs', :as => "order_logs"
      get 'find_variant_with_sku', to: 'orders#find_variant_with_sku'
    end
    get 'brands/remove_product_from_brand', to: "brands#remove_product_from_brand"
    get 'categories/remove_product_from_category', to: "categories#remove_product_from_category"
    resources :generals 
    resources :warehouses_roles
    resources :product_properties
    resources :child_categories
    resources :categories do
      get ':product_id/to_display', to: "categories#to_display", :as => "to_display"
      get 'make_active', to: "categories#make_active"
      collection { post :sort }
      collection { post :promotion_sort }
      collection { post :remove_product_from_category }
    end
    resources :types
    resources :images do
      collection { post :sort }
      collection { post :banner_sort }
      collection { post :parent_image_sort }
      collection { post :child_image_sort }
    end
    resources :invoices
    resources :products_tax_plans
    resources :child_products
    resources :product_shipping_plans    
    resources :inventories
    resources :values
    resources :specifications    
    resources :brands do
      collection { post :remove_product_from_brand }
      post :delete_selected, :on => :collection
      post :delete_selected_brand, :on => :collection
    end
    resources :product_questions
    resources :permissions

    resources :shipping_plans do
      resources :shipping_countries do
        resources :shipping_states do
          resources :shipping_cities do
            resources :shipping_costs
          end
        end
      end
    end
    
    resources :warehouses do
      resources :addresses
    end

    resources :vendors do
      resources :addresses
    end

    resources :products do
      get 'cod_activate', to: "products#cod_activate", :as => "cod_activate" 
      resources :variants do 
        resources :inventories do 
          resources :regulations
        end
        collection { post :sort }
      end
      collection { post :sort }
      collection { post :promotion_sort }
      collection { post :promotion_update }
    end
   
    get 'find_state_city_pincode', to: "countries#find_state_city_pincode", :as => "find_state_city_pincode" 
    get 'countries/autocomplete/:search_param', to: "countries#autocomplete", :as => "countries_autocomplete" 
    resources :countries do 
      collection { post :import }
      resources :states do
        collection { post :import } 
        
      end
    end
    
    resources :district_cities do
      collection { post :import }
      resources :pincodes
    end
    
    resources :users do
      get 'orders', to: 'users#orders', :as => "orders"
      resources :addresses
      resources :profiles, :except => [:index, :destroy]
    end

app/controllers/support/orders_controller.rb
class Support::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize  
  before_action :authorize_support
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :order_params, only: [:update]

  def index
    @param = params[:q] 
    @search = Admin::Order.all.search(params[:q])
    @orders = @search.result
    @wh_order = @search.result.where(:status => "wh").includes(:user) 
    @up_order = @search.result.where(:status => "up").includes(:user) 
    @search.build_condition
    @search.build_sort if @search.sorts.empty?
    if request.xhr?
      if params[:up_page].present?
        render :template => "support/orders/up_order_page.js.erb"
        @up_order = Admin::Order.up_orders.all.page(params[:up_page]).per(5).search(params[:q])
      elsif params[:wh_page].present?
        render :template => "support/orders/wh_order_page.js.erb"
        @wh_order = Admin::Order.wh_orders.all.page(params[:wh_page]).per(5).search(params[:q])
      else
        @render_path = support_orders_path
        @render_file = 'support/orders/index'
        render "remote_content/common_render.js.erb" 
      end         
    else
      render :template => "support/orders/index"
    end

  end 

  def edit
    @new_shipping_address = ShippingAddress.new
    @items = @order.order_items
    @order_revocation = @order.order_revocations.build 
    if request.xhr?
      @render_path = edit_support_order_path(@order)
      @render_file = 'support/orders/edit'
      render "remote_content/common_render.js.erb"          
    else
      render :template => "support/orders/edit"
    end
  end

  def show
    @all = @order.consignments
    @delivered = @order.consignments.where(:delivery_status => true)
    @notdelivered = @order.consignments.where(:delivery_status => false)
    @unprocess = @order.consignments.where(:delivery_status => nil,:conform => false)
    @processed = @order.consignments.where(:delivery_status => nil,:conform => true)
    @order_revocation = @order.order_revocations.build 
    if request.xhr?
      if params[:view].present?
        render :template => "admin/orders/admin_show.js.erb" 
      else
        @render_path = support_order_path(@order)
        @render_file = 'support/orders/show'
        render "remote_content/common_render.js.erb"
      end          
    else
      render :template => "support/orders/show"
    end 
  end
 
  def update
    if request.xhr? 
      if params[:admin_order][:for_check].present?
        @new_order_hash = params[:admin_order]
        render :template => "remote_content/order_edit_preview.js.erb"
      else
        if params[:admin_order][:shipping_address_id].present?
          if @order.status == "up" && @order.cancel.nil?
            @order.update(order_params)
            @order_log =  @order.create_order_log(current_user.id)
            @new_order_hash = params[:admin_order] 
            @new_order_hash[:order_items_attributes].each do |new_order_hash|
              @order_item_log = @order_log.order_item_logs.where(:variant_id => new_order_hash[1][:variant_id]).first
              @order_item_log.update(:reason => new_order_hash[1][:reason])
            end
            flash[:notice] = 'Order was successfully updated.'
            render :js => "window.location = '#{support_order_path(@order)}'"
          else
            flash[:notice] = 'Order cannot be updated.'
            render :js => "window.location = '#{support_order_path(@order)}'"
          end
        else
          if params[:admin_order][:warehouse_id].present?
            @order.update(:status => "wh")
            @order_log = @order.create_order_log(current_user.id)
            flash[:notice] = "Shipping Plan Added."
            render :template => "remote_content/order_warehouse.js.erb"
          else
            if params[:admin_order][:present_user].present?
              if @order.status == "up" && @order.check_consignment_status && @order.cancel.nil?
                @order.update(order_params)
                @order.create_order_log(current_user.id)
                render :template => "remote_content/order_warehouse.js.erb"
              else
                flash[:notice] = 'Sorry You Cannot Update This Order'
                render :template => "remote_content/order_warehouse.js.erb"
              end  
            end
          end
        end
      end 
    else 
      if @order.check_support_cancel_order_status
        if @order.payment_mode == 'COD'
          if params[:admin_order][:support_order_cancel].present?
            @order.update(order_params)
            @order.create_order_log(current_user.id)
            @notification= Admin::NotificationCustomer.first
            if @notification.present?
              if @notification.post_deli_cancel
                @order.order_cancel_sms 
                Admin::InvoiceMailer.email_order_cancelled(@order).deliver
              end
            end
            redirect_to support_order_path(@order), notice: 'Order was successfully Cancelled.'
          else
            redirect_to support_order_path(@order), notice: 'Order was successfully Cancelled.'
          end
        else
          if @order.update(:cancelled_by => current_user.id ,:cancel => params[:admin_order][:cancel], :remarks => params[:admin_order][:remarks])
            if params[:admin_order][:order_revocations_attributes].first[1][:revocation_mode] == "Cash Back"
              if params[:admin_order][:order_revocations_attributes].first[1][:bank_account_id].nil?
                @bankaccount = BankAccount.create(:name => params[:admin_order][:bank_accounts][:name], :num => params[:admin_order][:bank_accounts][:name], :bank_code => params[:admin_order][:bank_accounts][:ifsc_code], :user_id => @order.user_id)
                @bank_account_id = @bankaccount.id
              else
                @bank_account_id = params[:admin_order][:order_revocations_attributes].first[1][:bank_account_id] 
              end
              @revocation_mode = 'b'
            else
              @revocation_mode = 'v'
            end
            if @notification.present?
              if @notification.post_deli_cancel
                @order.order_cancel_sms 
                Admin::InvoiceMailer.email_order_cancelled(@order).deliver
              end
            end
            @order_revocation = @order.create_revocation_for_cancel
            @order_revocation.update(:bank_account_id =>  @bank_account_id,:revocation_mode => @revocation_mode)
            @order.create_order_log(current_user.id)
          else
            redirect_to support_order_path(@order), notice: 'Order Cannot Be Cancell Contact Our Support.'
          end
        end
      else
        redirect_to support_order_path(@order), notice: 'Order Cannot Be Cancell Contact Our Support.'
      end
    end
  end

  private 
    def set_order
      @order = Admin::Order.find(params[:id])
    end

    def order_params
      params.require(:admin_order).permit(:cancel, :remarks, :cancelled_by, :user_id, :pay_val, :cal_conf, :present_user, :prev_rec,  :shipping_address_id, :order_cost, :payment_mode, :payment_status, :order_number, :status,:warehouse_id, :prev_rec_reason, :pay_val_reason, :cal_conf_reason, order_items_attributes:[:id, :variant_id, :_destroy, :qty, :per_qty_price,:reason],consignments_attributes:[:id,:order_item_id,:warehouse_id,:consignment_cost],order_revocations_attributes:[:id, :revocation_mode ,:revocation_cost])
    end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
  def up_order_qty(variant)
  	up_qty = 0
    Admin::Order.where(:status => "up").each do |order|
	  up_item = order.order_items.where(:variant_id => variant.id).first
	  if up_item.present?
	    up_qty += up_item.qty
	  end
	end 
	return up_qty
  end
end

app/views/ranees_standard_view/orders/admin_show.html.erb
<div class="row">  
  <div class="col-xs-12 col-sm-2 left">
    <%= render partial: "layouts/shared/admin_sidebar" %>
  </div>
  <span class="order_id" style="display:none;"><%= admin_order_show_path( @order) %></span>
  <div class="col-xs-12 col-sm-10">
    <div class="border"><br/>
      <div class="pull-right">
	    <% if check_link(admin_order_logs_path(@order.id)) %>  
	      <%= link_to 'Order Logs', admin_order_logs_path, :order_id => @order.id, :class => "btn btn-primary btn-sm" %> 
	    <% end %>
	  </div> 
      <div class="pull-right">
	    <% if check_link(edit_user_order_path(@order.user_id, @order)) %>  
	      <%= link_to 'Edit Orders', admin_order_edit_path(@order), :class => "btn btn-primary btn-sm" %> 
	    <% end %>
	  </div> 
	  <div class="row">
        <div class="col-sm-6 col-xs-12">
        <ol class="breadcrumb">
          <% if check_link(admin_order_index_path) %>  
            <li><%= link_to "Orders", admin_order_index_path %></li>
          <% end %>
          <li class="active"><%= @order.order_number %></li>
        </ol>
        </div>
      </div>
    </div> 
    <br/>
    <% if @order.pay_val.nil? || @order.pay_val == false %>
      <span class="current_stage" style="display:none">0</span>
    <% elsif @order.cal_conf.nil? || @order.prev_rec.nil? || @order.cal_conf == false || @order.prev_rec == false %>
      <span class="current_stage" style="display:none">1</span>
    <% else %>
      <span class="current_stage" style="display:none">2</span>
    <% end %>
    <div class="col-sm-7 col-xs-12"> 
	    <div class="panel panel-info">
	      <div class="panel-heading text-center">
            <strong>ORDER DETAILS</strong>
          </div>
	      <div class="panel-body"><br/>
			<div class="row info-borders">
				<div class="col-sm-3 text-info"><strong>Order Number</strong></div>
				<div class="col-sm-9"><%= @order.order_number %></div>
			</div><br/>
			<div class="row info-borders">
				<div class="col-sm-3 text-info"><strong>Paymet Mode</strong></div>
				<div class="col-sm-9"><%= @order.payment_mode %></div>
			</div><br/>
			<div class="row info-borders">
				<div class="col-sm-3 text-info"><strong>Payment Status</strong></div>
				<div class="col-sm-9"><%= @order.payment_status %></div>
			</div><br/>
			<div class="row info-borders">
				<div class="col-sm-3 text-info"><strong>Order Cost</strong></div>
				<div class="col-sm-9"><%= @order.order_cost %></div>
			</div><br/>
			<div class="row info-borders">
				<div class="col-sm-3 text-info"><strong>Order Status</strong></div>
				<div class="col-sm-9"><%= @order.status %></div>
			</div><br/>
			<div class="row info-borders">
				<div class="col-sm-3 text-info"><strong>Location</strong></div>
				<div class="col-sm-9"><%= @order.location %><% if @order.ip.present? %>(<%= @order.ip %>)<% end %></div>
			</div><br/>
			<div class="row info-borders">
			  <div class="col-sm-3 text-info"><strong>Shipping Address</strong></div>
			  <div class="col-sm-9">
				<%= @order.shipping_address.name %><br/>
				<%= @order.shipping_address.add_line1 %>,
		        <%= @order.shipping_address.add_line2 %><br/>
		        <%= @order.shipping_address.state %>,
		        <%= @order.shipping_address.country %>-
		        <%= @order.shipping_address.c_code %><br/>
				<%= @order.shipping_address.pincode %><br/>
				<%= @order.shipping_address.phone %>
			  </div>
			</div>
		  </div>
		</div>
	    <div class="rejection_reason">
        <!-- Tabs -->
  		  <div id="wizard" class="swMain">
  			<ul>
  				<li>
  				  <a href="#step-1">
                <span class="stepNumber">1</span>
                <span class="stepDesc">
                   Payment Confirmation<br />
                   <small></small>
                </span></a></li>
  				<li><a href="#step-2">
                <span class="stepNumber">2</span>
                <span class="stepDesc">
                   User Verification<br />
                   <small></small>
                </span>
            </a></li>
  				<li><a href="#step-3">
                <span class="stepNumber">3</span>
                <span class="stepDesc">
                   Assigning Warehouse<br />
                   <small></small>
                </span>
             </a></li>
  			</ul>
          <%= form_for @order, :url => user_order_path(@order.user_id, @order),:remote =>true,:class => "edit_order_confirmation"  do |f| %>
            <%= f.hidden_field :present_user, :value => current_user.id.to_i %>
		    <input type='hidden' name="issubmit" value="1">
	  			<div id="step-1">	
		            <h2 class="StepTitle st text-info">Step 1: Payment Confirmation</h2><br/><br/>
		            <div class="row">
					  <div class="col-sm-5 col-xs-6">
					    <%= f.label :pay_val, "Payment Confirmation"%>
					  </div>
					  <div class="col-sm-6 col-xs-6">
					    <%= f.radio_button :pay_val, 'true' %> 
					    <%= label :pay_val, 'Approve' %>
					    <%= f.radio_button :pay_val, 'false' %>
					    <%= label :pay_val, 'Cancel' %><br/>
					    <span id="msg_username"></span>
					  <% if @order.pay_val == false %>
					    <% pay_val_reason_val = @order.order_logs.where(:order_attribute => "pay_val",:attr_value => "false" ).order('created_at DESC').first.rejection_reason.reason %>
	                    <div class="pay_val_reason"   >
	                  <% else %>
	                    <% pay_val_reason_val = "" %>
	                    <div class="pay_val_reason" style = "display:none">
	                  <% end %>
					      <%= f.label :pay_val_reason, "Reason" %>
					      <%= f.text_field :pay_val_reason,:class => "form-control",:value => pay_val_reason_val %>
					    </div>
					    <span id="msg_reason1"></span>
					  </div>
					</div>          			
	            </div>
	        </div>
	  			<div id="step-2">
	            <h2 class="StepTitle st text-info">Step 2: User Verification</h2>	<br/><br/>
	            <div class="row">
				    <div class="col-sm-4 col-xs-6">
				      <%= f.label :cal_conf, "Call Confirmation"%>
				    </div>
				    <div class="col-sm-7 col-xs-6">
				      <%= f.radio_button :cal_conf, 'true',:class => "cal_conf_class" %> 
				      <%= label :cal_conf, 'Approve' %>
				      <%= f.radio_button :cal_conf, 'false',:class => "cal_conf_class" %>
				      <%= label :cal_conf, 'Cancel' %><br/>
				      <span id="msg_firstname"></span>
				      <% if @order.cal_conf == false %>
					    <% cal_conf_reason_val = @order.order_logs.where(:order_attribute => "cal_conf",:attr_value => "false" ).order('created_at DESC').first.rejection_reason.reason %>
	                    <div class="cal_conf_reason" >
	                  <% else %>
	                    <% cal_conf_reason_val = "" %>
	                    <div class="cal_conf_reason" style = "display:none">
	                  <% end %>
                        <%= f.label :cal_conf_reason, "Reason" %>
				        <%= f.text_field :cal_conf_reason,:class => "form-control",:value =>cal_conf_reason_val  %>
				      </div><br/>
				      <span id="msg_reason2"></span>
				    </div>
				  </div><br/>
				  <div class="row">
				    <div class="col-sm-4 col-xs-6">
				      <%= f.label :prev_rec, "Previous Order History" %>
				    </div>
				    <div class="col-sm-7 col-xs-6">
				      <%= f.radio_button :prev_rec, 'true' %> 
				      <%= label :prev_rec, 'Approve' %>
				      <%= f.radio_button :prev_rec, 'false' %>
				      <%= label :prev_rec, 'Cancel' %><br/>
				      <span id="msg_gender"></span>
				      <% if @order.prev_rec == false %>
					    <% prev_rec_reason_val = @order.order_logs.where(:order_attribute => "prev_rec",:attr_value => "false" ).order('created_at DESC').first.rejection_reason.reason %>
	                    <div class="prev_rec_reason" >
	                  <% else %>
	                    <% prev_rec_reason_val = "" %>
	                    <div class="prev_rec_reason" style = "display:none">
	                  <% end %>
				        <%= f.label :prev_rec_reason, "Reason" %>
				        <%= f.text_field :prev_rec_reason,:class => "form-control",:value =>prev_rec_reason_val  %>
				      </div><br/>
				      <span id="msg_reason3"></span>
				    </div>
				  </div>
	        </div>  
	      <% end %>                     
	  		<div id="step-3">
	          <h2 class="StepTitle text-info">Step 3: Assigning Warehouse</h2><br/>
			  <div class="row consignment_warehouse">
				<%= render partial: "consignment_warehouse" %>
			  </div>	               				          
	        </div>
	  	  </div>
		<!-- End SmartWizard Content -->  		
	    </div>
    </div>
    <div class="col-sm-5 col-xs-12">
      <div class="panel panel-success">
        <div class="panel-heading text-center">
          <strong>ORDER ITEMS</strong>
        </div>
        <div class="panel-body">
          <div class="row text-center text-success borders">
            <div class="col-sm-2 col-xs-12"><strong>Variant</strong></div>
            <div class="col-sm-2 col-xs-12"><strong>Qty</strong></div>
            <div class="col-sm-2 col-xs-12"><strong>Shipping Plan</strong></div>
            <div class="col-sm-6 col-xs-12"><strong>Purchase Cost</strong></div>
          </div><br/>
          <% @order.cart_items.each do |cart_item| %>
            <% @variant = Admin::Variant.find(cart_item.variant_id) %>
            <% @shipping = Admin::Product.shipping_cost(@order.shipping_address.pincode, @variant.product, @variant) %>
            <% selling_price = Admin::Inventory.where(:variant_id => @variant.id).order('selling_price DESC').first.selling_price %>
            <div class="row text-center borders">
              <div class="col-sm-2 col-xs-12"><%= @variant.name %></div>
              <div class="col-sm-2 col-xs-12"><%= cart_item.qty %></div>
              <div class="col-sm-2 col-xs-12">
                <%= @variant.product.shipping_plans.first.name %>
              </div>
              <div class="col-sm-6 col-xs-12">RS. <%= cart_item.price %><br/>
                <span class="text-muted">
                  Selling Price: <%= selling_price %><br/>
                  Shipping Cost: <%= @shipping.cost %><br/>
                  Tax: <%= cart_item.price - (@shipping.cost + selling_price) %></span>
              </div>
            </div><br/>
          <% end %>
        </div>
      </div>
      <div class="panel panel-success">
        <div class="table-header">User Details(<%= @order.user.email %>)</div>
        <div class="panel-body user_details"><br/>
		  
        </div>
      </div>
    </div>
</div>
 <script>
 $(document).ready(function(){

 	var current_stage = parseInt($(".current_stage").text());
    $('#wizard').smartWizard({transitionEffect:'slideleft',onLeaveStep:leaveAStepCallback,selected: current_stage });
      function leaveAStepCallback(obj){
        var step_num= obj.attr('rel');
        return validateSteps(step_num);
      }
      if (current_stage == 2){
	      $(".stepContainer").css("height","300px");
	      $(".stepContainer").css("display","block");
      }
		});
  setTimeout(function() {
 	var url = $(".order_id").text();
    $.ajax({
      url: url,
      data: {},
      type: 'GET',
      success: function(data, event, status, xhr) {
      },
      error: function(data, event, status, xhr) {
      }
    });
  }, 1000);
 </script>

app/views/ranees_standard_view/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>